name: AST Transform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run AST transform
        run: npm run transform

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: transformed-js
          path: output.js