name: IPA Dump

on:
  workflow_dispatch:
    inputs:
      ipa_path:
        description: "上传的 IPA 文件路径（必须已砸壳）"
        required: true
        default: "MyApp.ipa"

jobs:
  dump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 安装 class-dump-z (下载 Release 二进制)
      - name: Install class-dump-z
        run: |
          curl -L https://github.com/zhlynn/class-dump-z/releases/download/0.2/class-dump-z.zip -o cdz.zip
          unzip cdz.zip
          chmod +x class-dump-z
          sudo mv class-dump-z /usr/local/bin/

      # 安装 swift-dump (源码编译)
      - name: Install swift-dump
        run: |
          git clone https://github.com/aidansteele/swift-dump.git
          cd swift-dump
          swift build -c release
          sudo cp .build/release/swift-dump /usr/local/bin/

      # 解压 IPA
      - name: Unzip IPA
        run: |
          mkdir work
          unzip -q ${{ github.event.inputs.ipa_path }} -d work
          APPDIR=$(find work -name "*.app" | head -n 1)
          echo "APPDIR=$APPDIR" >> $GITHUB_ENV
          BINARY=$(basename "$APPDIR" .app)
          echo "BINARY=$BINARY" >> $GITHUB_ENV
          echo "BINPATH=$APPDIR/$BINARY" >> $GITHUB_ENV

      # 提取 arm64 架构（class-dump/swift-dump 都更适配 arm64）
      - name: Extract arm64 binary
        run: |
          if lipo -info "$BINPATH" | grep -q arm64; then
            lipo "$BINPATH" -thin arm64 -output work/${BINARY}.arm64
            echo "BINPATH=work/${BINARY}.arm64" >> $GITHUB_ENV
          fi

      # Objective-C 头文件导出
      - name: Class-dump (ObjC headers)
        run: |
          mkdir -p DumpResult/ObjCHeaders
          class-dump-z -H "$BINPATH" -o DumpResult/ObjCHeaders || echo "No ObjC classes"

      # Swift 符号导出
      - name: Swift-dump (Swift symbols)
        run: |
          mkdir -p DumpResult/SwiftSymbols
          swift-dump all "$BINPATH" > DumpResult/SwiftSymbols/swift_all.txt || echo "No Swift symbols"

      # 上传结果 (artifact)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipa-dump-result
          path: DumpResult
